org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=false
loom.ignoreDependencyLoomVersionValidation=true

minecraft_version=26.1.2
loader_version=0.19.2
create_fly_version=26.1.2-6.0.9-4
cloth_config_version=26.1.154
modmenu_version=18.0.0
mod_version=1.1.2
maven_group=awa.Aether_254
archives_base_name=create-unrestricted-vault
